### ISSUE TITLE
java.nio.file.accessdeniedexception

### ISSUE THREAD

**Issue by literaleon** [SneakySpook/Tickompiler#14]
When running "p FOLDERTWO base.bin", I get the an error, which it says is caused by java.nio.file.accessdeniedexception: base.bin
What am I doing wrong?

**Comment by flvinny** [comment]
I'm assuming you're following a tutorial on combining tickflow mods, such as [this one](https://gamebanana.com/threads/222265).
Make sure you're not missing the ``base.bin`` file, which should be located in the same folder as ``FOLDERTWO`` - like this:
```
./
├─ FOLDERONE/
├─ FOLDERTWO/
├─ base.bin
├─ ...etc...
```
