### ISSUE TITLE
"An illegal reflective access operation has occurred"

### ISSUE THREAD

**Issue by BobTheNerd10** [SneakySpook/Tickompiler#9]
When compiling, this occurs

c tickflow tempo
Compiling 1 file(s)
Compiling tickflow\rvlRocket.tickflow
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.parboiled.transform.AsmUtils (file:/C:/Users/BobTh/Desktop/Modding%20Workshop/Rhythm%20Heaven%20Megamix/Tools/Tickompiler/tickompiler.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.parboiled.transform.AsmUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Compiled tickflow\rvlRocket.tickflow -> 1423.9809 ms

I've tested packing and extracting as well, as far as I can tell this is the only command it affects. The compile command does work in its entirety.

**Comment by BobTheNerd10** [comment]
To clarify this happens with files directly extracted from the game as well, not just modified files

**Comment by chrislo27** [comment]
This is a warning introduced by Java 9 to 15 as part of the Parboiled library, and is not related to Tickompiler code. It becomes an error in Java 16. Per [the README](https://github.com/rhmodding/Tickompiler#running-the-program), you can mitigate the issue by adding the `--add-opens` JVM argument:
```
java --add-opens java.base/java.lang=ALL-UNNAMED -jar tickompiler.jar --help
```

**Comment by chrislo27** [comment]
The following issue with Java 16 and newer is also resolved with the `--add-opens` JVM argument:
```
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (rhmodding.tickompiler.cli.CompileCommand@4cf4d528): java.lang.RuntimeException: Error creating extended parser class: Could not determine whether class 'rhmodding.tickompiler.compiler.TickflowParser$$parboiled' has already been loaded
```
